# Service definition
name: transceiver
description: Replicates the controller mechanism by using remote control input

# No dependencies at start
dependencies: []

# No outputs
outputs: 
  - name: decision
    address: tcp://localhost:5556

options:
 - name: forwardingserver-address
   type: string
   mutable: false
   default: http://localhost:7500 # Change this to the IP address that of the forwarding server
