name: test
on:
  push:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  lint:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      - run: sudo apt update && sudo apt install pkg-config libzmq3-dev protobuf-compiler
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          skip-pkg-cache: true
  tests:
    name: automated tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      - run: sudo apt update && sudo apt install pkg-config libzmq3-dev protobuf-compiler
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Run tests
        run: make test
